const express = require('express');
const router = express.Router();
const controller = require('../controllers/productosController');
router.get('/', controller.getAll);
router.get('/sugerencia-compra', controller.getSugerenciaCompra);
router.put('/lead-time-proveedor', controller.guardarLeadTimeProveedor);
router.post('/guardar-minimos', controller.guardarMinimos);
router.get('/alertas/stock', controller.getAlertas);
router.get('/stock/transito', controller.getTransito);
router.get('/stock/ajustes', controller.getHistorialAjustes);
router.get('/imagenes/todas', controller.getImagenes);
router.post('/recalcular-stock-minimo', controller.recalcularStockMinimo);
router.get('/:id', controller.getById);
router.post('/', controller.create);
router.put('/:id', controller.update);
router.delete('/:id', controller.remove);
router.put('/:id/ajustar-stock', controller.ajustarStock);
router.put('/:id/estado', controller.cambiarEstado);
router.get('/:id/imagen', controller.getImagen);
router.put('/:id/imagen', controller.guardarImagen);
router.delete('/:id/imagen', controller.borrarImagen);
module.exports = router;