const express = require('express');
const router = express.Router();
const controller = require('../controllers/productosController');
router.get('/', controller.getAll);
router.get('/sugerencia-compra', controller.getSugerenciaCompra);
router.get('/alertas/stock', controller.getAlertas);
router.get('/stock/transito', controller.getTransito);
router.get('/stock/ajustes', controller.getHistorialAjustes);
router.post('/recalcular-stock-minimo', controller.recalcularStockMinimo);
router.get('/:id', controller.getById);
router.post('/', controller.create);
router.put('/:id', controller.update);
router.delete('/:id', controller.remove);
router.put('/:id/ajustar-stock', controller.ajustarStock);
module.exports = router;