// Estructura de la base (tablas, columnas, secuencias, restricciones e indices) de un "cajon"
// (schema de Postgres). Sirve para:
//   - crear el cajon de un negocio nuevo, igual al del negocio modelo pero vacio
//   - poner al dia el cajon de un negocio cuando el sistema suma tablas o columnas
//   - exportar la estructura (sin datos) para soporte
// Todo se lee y se crea con el search_path puesto en el cajon, asi los nombres salen sin
// el prefijo del schema y sirven para cualquier otro.

const id = (n) => '"' + String(n).replace(/"/g, '""') + '"';

function nombreSchemaValido(s) {
  return typeof s === 'string' && /^[a-z_][a-z0-9_]{0,50}$/.test(s);
}

// cli: una conexion (client de pg). Devuelve { tablas: [...], secuencias: [...] }
async function leerEstructura(cli, schema) {
  if (!nombreSchemaValido(schema)) throw new Error('Nombre de schema inválido');
  await cli.query('SET search_path TO ' + id(schema));
  try {
    const tablas = (await cli.query(
      `SELECT c.oid, c.relname AS nombre
         FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = $1 AND c.relkind = 'r' ORDER BY c.relname`, [schema])).rows;

    const cols = (await cli.query(
      `SELECT a.attrelid AS oid, a.attname AS nombre, format_type(a.atttypid, a.atttypmod) AS tipo,
              a.attnotnull AS no_nulo, a.attidentity AS identidad, a.attgenerated AS generada,
              pg_get_expr(d.adbin, d.adrelid) AS defecto,
              pg_get_serial_sequence(quote_ident($1) || '.' || quote_ident(c.relname), a.attname) AS secuencia
         FROM pg_attribute a
         JOIN pg_class c ON c.oid = a.attrelid
         JOIN pg_namespace n ON n.oid = c.relnamespace
         LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
        WHERE n.nspname = $1 AND c.relkind = 'r' AND a.attnum > 0 AND NOT a.attisdropped
        ORDER BY a.attrelid, a.attnum`, [schema])).rows;

    const cons = (await cli.query(
      `SELECT k.conrelid AS oid, k.conname AS nombre, k.contype AS tipo, pg_get_constraintdef(k.oid) AS def
         FROM pg_constraint k JOIN pg_namespace n ON n.oid = k.connamespace
        WHERE n.nspname = $1 AND k.conrelid <> 0 AND k.contype IN ('p','u','c','f')
        ORDER BY k.conname`, [schema])).rows;

    // Indices que no son de una restriccion (esos se crean solos con la restriccion)
    const inds = (await cli.query(
      `SELECT i.indrelid AS oid, ic.relname AS nombre, pg_get_indexdef(i.indexrelid) AS def
         FROM pg_index i
         JOIN pg_class ic ON ic.oid = i.indexrelid
         JOIN pg_namespace n ON n.oid = ic.relnamespace
        WHERE n.nspname = $1 AND NOT EXISTS (SELECT 1 FROM pg_constraint k WHERE k.conindid = i.indexrelid)
        ORDER BY ic.relname`, [schema])).rows;

    const secs = (await cli.query(
      `SELECT sequencename AS nombre, data_type::text AS tipo, increment_by::text AS incremento, start_value::text AS inicio
         FROM pg_sequences WHERE schemaname = $1 ORDER BY sequencename`, [schema])).rows;

    // pg_get_indexdef pone el schema adelante de la tabla: se saca para que sirva en cualquier cajon
    const prefijo = new RegExp(' ON (ONLY )?("?)' + schema + '\\2\\.');
    const porOid = {};
    tablas.forEach(t => { porOid[t.oid] = { nombre: t.nombre, columnas: [], restricciones: [], indices: [] }; });
    cols.forEach(c => porOid[c.oid] && porOid[c.oid].columnas.push({
      nombre: c.nombre, tipo: c.tipo, no_nulo: c.no_nulo, defecto: c.defecto, identidad: c.identidad || '', generada: c.generada || '',
      secuencia: c.secuencia ? c.secuencia.replace(/^.*\./, '').replace(/^"|"$/g, '') : null,
    }));
    cons.forEach(k => porOid[k.oid] && porOid[k.oid].restricciones.push({ nombre: k.nombre, tipo: k.tipo, def: k.def }));
    inds.forEach(i => porOid[i.oid] && porOid[i.oid].indices.push({ nombre: i.nombre, def: i.def.replace(prefijo, (m, solo) => ' ON ' + (solo || '')) }));
    return { tablas: tablas.map(t => porOid[t.oid]), secuencias: secs };
  } finally {
    await cli.query('RESET search_path');
    cli.__schema = null; // config/database.js vuelve a apuntarla al cajon que corresponda
  }
}

function defColumna(c) {
  let s = id(c.nombre) + ' ' + c.tipo;
  if (c.generada === 's') s += ' GENERATED ALWAYS AS (' + c.defecto + ') STORED';
  else if (c.identidad === 'a') s += ' GENERATED ALWAYS AS IDENTITY';
  else if (c.identidad === 'd') s += ' GENERATED BY DEFAULT AS IDENTITY';
  else if (c.defecto !== null && c.defecto !== undefined) s += ' DEFAULT ' + c.defecto;
  if (c.no_nulo) s += ' NOT NULL';
  return s;
}

// Deja el cajon `schema` con todo lo que tiene `modelo` (lo que falte: tablas, columnas,
// secuencias, restricciones, indices). No borra ni cambia nada de lo que ya existe, y no toca datos.
// Devuelve cuantas cosas agrego. Se usa dentro de una transaccion del que llama.
async function aplicarEstructura(cli, schema, modelo) {
  if (!nombreSchemaValido(schema)) throw new Error('Nombre de schema inválido');
  await cli.query('CREATE SCHEMA IF NOT EXISTS ' + id(schema));
  const actual = await leerEstructura(cli, schema);
  const hayTabla = {}; actual.tablas.forEach(t => { hayTabla[t.nombre] = t; });
  const haySec = new Set(actual.secuencias.map(s => s.nombre));
  const hecho = { tablas: 0, columnas: 0, secuencias: 0, restricciones: 0, indices: 0 };

  await cli.query('SET search_path TO ' + id(schema));
  try {
    // Las secuencias de columnas IDENTITY las crea Postgres sola junto con la columna
    const deIdentidad = new Set();
    modelo.tablas.forEach(t => t.columnas.forEach(c => { if (c.identidad && c.secuencia) deIdentidad.add(c.secuencia); }));
    for (const s of modelo.secuencias) {
      if (haySec.has(s.nombre) || deIdentidad.has(s.nombre)) continue;
      await cli.query('CREATE SEQUENCE ' + id(s.nombre) + ' AS ' + s.tipo + ' INCREMENT BY ' + s.incremento + ' START WITH ' + s.inicio);
      hecho.secuencias++;
    }
    const duenos = [];
    for (const t of modelo.tablas) {
      const ya = hayTabla[t.nombre];
      if (!ya) {
        await cli.query('CREATE TABLE ' + id(t.nombre) + ' (' + t.columnas.map(defColumna).join(', ') + ')');
        hecho.tablas++;
        t.columnas.forEach(c => { if (c.secuencia && !c.identidad) duenos.push([c.secuencia, t.nombre, c.nombre]); });
      } else {
        const tiene = new Set(ya.columnas.map(c => c.nombre));
        for (const c of t.columnas) {
          if (tiene.has(c.nombre)) continue;
          await cli.query('ALTER TABLE ' + id(t.nombre) + ' ADD COLUMN ' + defColumna(c));
          hecho.columnas++;
          if (c.secuencia && !c.identidad) duenos.push([c.secuencia, t.nombre, c.nombre]);
        }
      }
    }
    for (const [sec, tabla, col] of duenos) {
      await cli.query('ALTER SEQUENCE ' + id(sec) + ' OWNED BY ' + id(tabla) + '.' + id(col));
    }
    // Primero claves y unicos (las claves foraneas los necesitan), al final las foraneas
    const orden = { p: 0, u: 1, c: 2, f: 3 };
    const todas = [];
    modelo.tablas.forEach(t => t.restricciones.forEach(k => todas.push([t, k])));
    todas.sort((a, b) => orden[a[1].tipo] - orden[b[1].tipo]);
    for (const [t, k] of todas) {
      const ya = hayTabla[t.nombre];
      if (ya && ya.restricciones.some(x => x.nombre === k.nombre)) continue;
      await cli.query('ALTER TABLE ' + id(t.nombre) + ' ADD CONSTRAINT ' + id(k.nombre) + ' ' + k.def);
      hecho.restricciones++;
    }
    for (const t of modelo.tablas) {
      const ya = hayTabla[t.nombre];
      for (const i of t.indices) {
        if (ya && ya.indices.some(x => x.nombre === i.nombre)) continue;
        await cli.query(i.def);
        hecho.indices++;
      }
    }
  } finally {
    await cli.query('RESET search_path');
    cli.__schema = null; // config/database.js vuelve a apuntarla al cajon que corresponda
  }
  return hecho;
}

// Para comparar dos cajones en las pruebas: una firma de texto de la estructura
function firma(est) {
  return JSON.stringify({
    t: est.tablas.map(t => [t.nombre, t.columnas.map(c => [c.nombre, c.tipo, c.no_nulo, c.defecto, c.identidad, c.generada, c.secuencia]),
      t.restricciones.map(k => [k.nombre, k.tipo, k.def]), t.indices.map(i => [i.nombre, i.def])]),
    s: est.secuencias.map(s => [s.nombre, s.tipo, s.incremento, s.inicio]),
  });
}

module.exports = { leerEstructura, aplicarEstructura, nombreSchemaValido, firma };
